maltarami/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('translate/', include('translate.urls'))
]

translate/urls.py
from django.urls import path
from . import views

app_name = 'translate'

urlpatterns = [
    path('', views.index, name='index'),
    path('model/', views.call_model.as_view(), name='model')
]

translate/models.py
from django.db import models

# Create your models here.

translate/views.py
from django.shortcuts import render
from .apps import TranslateConfig

# Create your views here.
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

class call_model(APIView):
    def post(self, request):
        if request.method == 'POST':
            sentence = request.GET.get('sentence')
            response = TranslateConfig.predictor(sentence)
            context = {'response':response}
            return render(request, 'translate/index.html', context)
        else:
            return render(request, 'translate/index.html')

def index(request):
    return render(request, 'translate/index.html')

maltarami/templates/base.html
<!-- maltarami/templates/base.html -->

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>말따라미</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="css/landing-page.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-light bg-light static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Maltarami</a>
      <a class="btn btn-primary" href="#">Home</a>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">About</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contact</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2019. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

translate/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <!-- Masthead -->
  <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">말투를 재미있게 바꿔봐요!</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form action = "{% url 'translate:model' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="text" class="form-control form-control-lg" placeholder="문장을 입력해 주세요.">
              </div>
              <div class="col-12 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-primary">새로운 말투로 바꾸기!</button>
              </div>
            </div>
          </form>
          {% if translated_sent %}
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <h3>{{ translated_sent }}</h3>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </header>
{% endblock %}